### ISSUE TITLE
"Free Disk Space" widget puts all Silicon Macs in the < 5GB category

### ISSUE THREAD

**Issue by aysiu** [munkireport/disk_report#18]
## Steps to replicate
1. Click on the **< 5GB** red part of the **Free Disk Space** widget.
2. See a Silicon Mac in there with partitions of `/System/Volumes/iSCPreboot`, `/System/Volumes/xarts`, and `/System/Volumes/Hardware` reporting with **Free** space as **0**.
3. Click on that Mac, and scroll down to see the visual chart widget display the correct amount of free disk space.
4. Show the summary page for that Mac, and see the **Storage** widget also showing the correct **Free** disk space.

**Comment by tuxudo** [comment]
These volumes should now all be hidden on the python 3 version of this module

**Comment by tuxudo** [comment]
Resolved with version v4.1 of the module
