### ISSUE TITLE
Feature request: hide new system volumes

### ISSUE THREAD

**Issue by flammable** [munkireport/disk_report#19]
Related to #18, there are a number of extra, hidden volumes on the Apple Silicon and Monterey Macs that should probably be excluded. [Here's a good breakdown of why they exist.](https://eclecticlight.co/2021/12/16/boot-disk-layout-in-macos-monterey/)

When I view Listings > Storage, I see a few examples:

/System/Volumes/xarts
/System/Volumes/Hardware
/System/Volumes/iSCPreboot
/System/Volumes/Update/SFR/mnt1

I use the Storage listing to see which Macs are low on disk space, but since these extra volumes has 0 kb of free space, they appear first in the list.

**Comment by tuxudo** [comment]
These will be hidden on the python 3 version of this script

**Comment by tuxudo** [comment]
Resolved with version v4.1 of the module
