### ISSUE TITLE
Total and free intermittent display in device tab

### ISSUE THREAD

**Issue by ofirgalcon** [munkireport/disk_report#24]
It's showing OK in list view

<img width="519" alt="image" src="https://user-images.githubusercontent.com/16665880/232496624-d9c69511-79fb-4c7c-8f2b-50b4bf59e029.png">

But not in device view (in Firefox) 

<img width="1188" alt="image" src="https://user-images.githubusercontent.com/16665880/232497516-49e2c312-52e5-46fe-9a90-4c1ba3d40c6e.png">

Console shows these errors: 

`This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”.`

**Comment by ofirgalcon** [comment]
Sometimes it displays a 'mini' version

<img width="1575" alt="image" src="https://user-images.githubusercontent.com/16665880/232499186-ab9dba1b-5a3c-40c7-9b09-6262e71b6530.png">

**Comment by tuxudo** [comment]
Fixed in v5.0 of module.
